#include "qfakturatemplate.h"

QFakturaTemplate::QFakturaTemplate(QWidget *parent) : QWidget(parent)
{

}
QString QFakturaTemplate::SetHtmlStyle()
{
    QString strStyle =
            "    <style>"
            "    .invoice-box{"
            "        max-width:800px;"
            "        margin:auto;"
            "        padding:30px;"
            "        border:1px solid #eee;"
            "        box-shadow:0 0 10px rgba(0, 0, 0, .15);"
            "        font-size:16px;"
            "        line-height:24px;"
            "        font-family:'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;"
            "        color:#555;"
            "    }"
            "    "
            "    .invoice-box table{"
            "        width:100%;"
            "        line-height:inherit;"
            "        text-align:left;"
            "    }"
            "    "
            "    .invoice-box table td{"
            "        padding:5px;"
            "        vertical-align:top;"
            "    }"
            "    "
            "    .invoice-box table tr td:nth-child(2){"
            "        text-align:right;"
            "    }"
            "    "
            "    .invoice-box table tr.top table td{"
            "        padding-bottom:20px;"
            "    }"
            "    "
            "    .invoice-box table tr.top table td.title{"
            "        font-size:45px;"
            "        line-height:45px;"
            "        color:#333;"
            "    }"
            "    "
            "    .invoice-box table tr.information table td{"
            "        padding-bottom:40px;"
            "    }"
            "    "
            "    .invoice-box table tr.heading td{"
            "        background:#eee;"
            "        border-bottom:1px solid #ddd;"
            "        font-weight:bold;"
            "    }"
            "    "
            "    .invoice-box table tr.details td{"
            "        padding-bottom:20px;"
            "    }"
            "    "
            "    .invoice-box table tr.item td{"
            "        border-bottom:1px solid #eee;"
            "    }"
            "    "
            "    .invoice-box table tr.item.last td{"
            "        border-bottom:none;"
            "    }"
            "    "
            "    .invoice-box table tr.total td:nth-child(2){"
            "        border-top:2px solid #eee;"
            "        font-weight:bold;"
            "    }"
            "    "
            "    @media only screen and (max-width: 600px) {"
            "        .invoice-box table tr.top table td{"
            "            width:100%;"
            "            display:block;"
            "            text-align:center;"
            "        }"
            "        "
            "        .invoice-box table tr.information table td{"
            "            width:100%;"
            "            display:block;"
            "            text-align:center;"
            "        }"
            "    }"
            "    </style>";
            return strStyle;
}
QString QFakturaTemplate::setTopHtml()
{
    QString sb =
            "<!doctype html>"
            "<html>";
    return sb;
}
QString QFakturaTemplate::setEndHtml()
{
    QString sb =
            "</html>";
    return sb;
}
QString QFakturaTemplate::setHtmlHead(QString htmlStyle){

    QString sb =
    "<head>"
    "    <meta charset=\"utf-8\">"
    "    <title>A simple, clean, and responsive HTML invoice template</title>"
    "    "
    + htmlStyle +
    "<head>";
    return sb;
}
QString QFakturaTemplate::setHtmlBody(){
    QString sb =
    "<body>"
    "    <div class=\"invoice-box\">"
    "        <table cellpadding=\"0\" cellspacing=\"0\">"
    "            <tr class=\"top\">"
    "                <td colspan=\"2\">"
    "                    <table>"
    "                        <tr>"
    "                            <td class=\"title\">"
    "                                <img src=\"http://nextstepwebs.com/images/logo.png\" style=\"width:100%; max-width:300px;\">"
    "                            </td>"
    "                            "
    "                            <td>"
    "                                Invoice #: 123<br>"
    "                                Created: January 1, 2015<br>"
    "                                Due: February 1, 2015"
    "                            </td>"
    "                        </tr>"
    "                    </table>"
    "                </td>"
    "            </tr>"
    "            "
    "            <tr class=\"information\">"
    "                <td colspan=\"2\">"
    "                    <table>"
    "                        <tr>"
    "                            <td>"
    "                                Next Step Webs, Inc.<br>"
    "                                12345 Sunny Road<br>"
    "                                Sunnyville, TX 12345"
    "                            </td>"
    "                            "
    "                            <td>"
    "                                Acme Corp.<br>"
    "                                John Doe<br>"
    "                                john@example.com"
    "                            </td>"
    "                        </tr>"
    "                    </table>"
    "                </td>"
    "            </tr>"
    "            "
    "            <tr class=\"heading\">"
    "                <td>"
    "                    Payment Method"
    "                </td>"
    "                "
    "                <td>"
    "                    Check #"
    "                </td>"
    "            </tr>"
    "            "
    "            <tr class=\"details\">"
    "                <td>"
    "                    Check"
    "                </td>"
    "                "
    "                <td>"
    "                    1000"
    "                </td>"
    "            </tr>"
    "            "
    "            <tr class=\"heading\">"
    "                <td>"
    "                    Item"
    "                </td>"
    "                "
    "                <td>"
    "                    Price"
    "                </td>"
    "            </tr>"
    "            "
    "            <tr class=\"item\">"
    "                <td>"
    "                    Website design"
    "                </td>"
    "                "
    "                <td>"
    "                    $300.00"
    "                </td>"
    "            </tr>"
    "            "
    "            <tr class=\"item\">"
    "                <td>"
    "                    Hosting (3 months)"
    "                </td>"
    "                "
    "                <td>"
    "                    $75.00"
    "                </td>"
    "            </tr>"
    "            "
    "            <tr class=\"item last\">"
    "                <td>"
    "                    Domain name (1 year)"
    "                </td>"
    "                "
    "                <td>"
    "                    $10.00"
    "                </td>"
    "            </tr>"
    "            "
    "            <tr class=\"total\">"
    "                <td></td>"
    "                "
    "                <td>"
    "                   Total: $385.00"
    "                </td>"
    "            </tr>"
    "        </table>"
    "    </div>"
    "</body>";
    return sb;
}


QString QFakturaTemplate::setFaktura()
{
    QString fakt = "";
    fakt += setTopHtml();

    fakt += setHtmlHead(SetHtmlStyle());
    fakt += setHtmlBody();
    fakt += setEndHtml();
    return fakt;
}


QString QFakturaTemplate::setFaktura2(faktura_trans& fakturaData)
{
    QString fakt =

           "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">"
           "<html xmlns=\"http://www.w3.org/1999/xhtml\">"
           "<head><title>"
           "	Invoice Template"
           "</title></head>"
           "<body>"
           "    <form name=\"form1\" method=\"post\" action=\"./InvoiceTemplate.aspx\" id=\"form1\">"
           "<div>"
           "<input type=\"hidden\" name=\"__VIEWSTATE\" id=\"__VIEWSTATE\" value=\"/wEPDwUKMTAxMDE3NjgwOA9kFgICAw9kFhICAQ8WAh4EVGV4dAUNQ3VzdG9tZXIgTmFtZWQCAw8WAh8ABRIxMjM0NSBUaGlzIFN0cmVldCBkAgUPFgIfAGRkAgcPFgIfAAUVVGVsOiAoMzEwKSA1NTUtNTU1NTU1ZAIJDxYCHwAFEmN1c3RvbWVyQGVtYWlsLmNvbWQCCw8WAh8ABRBPY3RvYmVyIDAxLCAyMDE2ZAINDxYCHwAFBTMwNjQzZAIPDzwrABEDAA8WBh4LXyFEYXRhQm91bmRnHgtfIUl0ZW1Db3VudAIDHgdWaXNpYmxlZ2QBEBYAFgAWAAwUKwAAFgJmD2QWCAIBD2QWDGYPDxYCHwAFAzEyM2RkAgEPDxYCHwAFCVByb2R1Y3QgMWRkAgIPDxYCHwAFFVByb2R1Y3QgMSBEZXNjcmlwdGlvbmRkAgMPDxYCHwAFBTEwLjAwZGQCBA8PFgIfAAUBMWRkAgUPDxYCHwAFBTEwLjAwZGQCAg9kFgxmDw8WAh8ABQMxMjNkZAIBDw8WAh8ABQlQcm9kdWN0IDFkZAICDw8WAh8ABRVQcm9kdWN0IDEgRGVzY3JpcHRpb25kZAIDDw8WAh8ABQUxMC4wMGRkAgQPDxYCHwAFATFkZAIFDw8WAh8ABQUxMC4wMGRkAgMPZBYMZg8PFgIfAAUDMTIzZGQCAQ8PFgIfAAUJUHJvZHVjdCAxZGQCAg8PFgIfAAUVUHJvZHVjdCAxIERlc2NyaXB0aW9uZGQCAw8PFgIfAAUFMTAuMDBkZAIEDw8WAh8ABQExZGQCBQ8PFgIfAAUFMTAuMDBkZAIEDw8WAh8DaGRkAhMPDxYCHwAFBTMwLjAwZGQYAQUJaXRlbXNHcmlkDzwrAAwBCAIBZBqNEZzf1UIY8Qy3+cuxUK0XnekiBlhYWb6e1brCO4rs\" />"
           "</div>"
           "<div>"
           "	<input type=\"hidden\" name=\"__VIEWSTATEGENERATOR\" id=\"__VIEWSTATEGENERATOR\" value=\"86DD59D6\" />"
           "</div>"
           "        <div>"
           "            <table width=\"800\">"
           "                <tr>"
           "                    <td style=\"width: 100%\">"
           "                        <table>"
           "                            <tr>"
           "                                <td style=\"width: 787px\" align=\"center\">"
           "                                    <img alt=\"Logo Image\" src=\"logo.png\" /></a>"
           "                                </td>"
           "                            </tr>"
           "                        </table>"
           "                    </td>"
           "                </tr>"
           "                <tr>"
           "                    <td>"
           "                    </td>"
           "                </tr>"
           "                <tr>"
           "                    <td style=\"width: 100%; height: 163px;\">"
           "                        <table  width=\"100%\">"
           "                            <tr>"
           "                                <td style=\"font-family: Arial\">"
           "                                    <table >"
           "                                        <tr>"
           "                                            <td style=\"font-weight: bold\">"
           "                                                Customer Name</td>"
           "                                        </tr>"
           "                                        <tr>"
           "                                            <td>"
           "                                                12345 This Street &nbsp;</td>"
           "                                        </tr>"
           "                                        <tr>"
           "                                            <td>"
           "                                                </td>"
           "                                        </tr>"
           "                                        <tr>"
           "                                            <td>"
           "                                                Tel: (310) 555-555555</td>"
           "                                        </tr>"
           "                                        <tr>"
           "                                            <td style=\"color: blue\">"
           "                                                customer@email.com</td>"
           "                                        </tr>"
           "                                    </table>"
           "                                </td>"
           "                                <td valign=\"top\" style=\"width: 395px\" align=\"right\">"
           "                                    <table >"
           "                                        <tr>"
           "                                            <td style=\"background-color: #F5F5F5; font-weight: bold; font-family: Arial;\" align=\"left\">"
           "                                                Invoice Date"
           "                                            </td>"
           "                                            <td>"
           "                                                &nbsp;</td>"
           "                                            <td style=\"background-color: #F5F5F5; font-weight: bold; font-family: Arial;\" align=\"left\">"
           "                                                Invoice Num"
           "                                            </td>"
           "                                        </tr>"
           "                                        <tr>"
           "                                            <td align=\"left\">"
           "                                                October 01, 2016&nbsp;</td>"
           "                                            <td>"
           "                                                &nbsp;</td>"
           "                                            <td align=\"left\">"
           "                                                30643</td>"
           "                                        </tr>"
           "                                    </table>"
           "                                </td>"
           "                            </tr>"
           "                        </table>"
           "                    </td>"
           "                </tr>"
           "                <tr>"
           "                    <td style=\"height: 33px; font-weight: bold; font-family: Arial;\">"
           "                        Report Items:</td>"
           "                </tr>"
           "                <tr>"
           "                    <td align=\"left\" style=\"width: 100%;\">"
           "                        <table width=\"100%\">"
           "                            <tr>"
           "                                <td>"
           "                                    <div>"
           "	<table cellspacing=\"0\" cellpadding=\"5\" rules=\"all\" border=\"1\" id=\"itemsGrid\" style=\"border-style:Double;font-family:Arial;width:100%;border-collapse:collapse;\">"
           "		<tr style=\"background-color:PeachPuff;\">"
           "			<th scope=\"col\">Code</th><th scope=\"col\">Name</th><th scope=\"col\">Description</th><th scope=\"col\">Price</th><th scope=\"col\">Quantity</th><th align=\"center\" scope=\"col\">Item Price</th>";
           for (int i = 0; i < fakturaData.data2.count(); i++ )
           {
            QString tempItem = "</tr><tr style=\"font-style:normal;\">"
                               "<td style=\"background-color:AliceBlue;\">%Id%</td>"
                               "<td>%Product%</td>"
                               "<td>%Product_Description%</td>"
                               "<td>%Cena%</td>"
                               "<td>%Kol%</td>"
                               "<td align=\"center\" style=\"background-color:#E0E0E0;font-weight:bold;\">%Iznos%</td>";

           tempItem.replace("%Id%",fakturaData.data2[i].artikal_id);
           tempItem.replace("%Product%",fakturaData.data2[i].artikal_naziv);
           tempItem.replace("%Product_Description%","");
           tempItem.replace("%Cena%",fakturaData.data2[i].izl_cena_so_ddv_prod);
           tempItem.replace("%Kol%",fakturaData.data2[i].kol);
           tempItem.replace("%Iznos%",fakturaData.data2[i].izl_prod_iznos_so_ddv);


           fakt += tempItem;
           }

           fakt +=
           "		</tr>"
           "	</table>"
           "</div>"
           "                                </td>"
           "                            </tr>"
           "                        </table>"
           "                    </td>"
           "                </tr>"
           "                <tr>"
           "                    <td style=\"height: 21px; width: 754px;\">"
           "                    </td>"
           "                </tr>"
           "                <tr>"
           "                    <td align=\"right\" style=\"width: 754px\">"
           "                        <table >"
           "                            <tr>"
           "                                <td>"
           "                                </td>"
           "                                <td>"
           "                                    <span id=\"lblTotal\" style=\"color:Blue;font-family:Arial;font-size:Medium;font-weight:bold;text-decoration:underline;\">Total: </span></td>"
           "                                <td>"
           "                                    &nbsp;"
           "                                </td>"
           "                                <td>"
           "                                    <span id=\"lblTotalPrice\" style=\"color:Black;background-color:#E0E0E0;font-family:Arial;font-weight:bold;\">30.00</span></td>"
           "                            </tr>"
           "                        </table>"
           "                    </td>"
           "                </tr>"
           "            </table>"
           "        </div>"
           "    </form>"
           "</body>"
           "</html>";


    return fakt;
}

